### ISSUE TITLE
Failed unittests

### ISSUE THREAD

**Issue by Devel484** [Mai-Te-Pora/tradehub-python#9] opened 2021-01-28 21:12 UTC
Unittest are failing because the Sentry Node does not return a result in time sometimes.

I used a retry and raise functionality, maybe have a look at [request_get](https://github.com/Mai-Te-Pora/endpoint-addon-py/blob/main/utils/__init__.py)

**Comment by switcheolytics** [comment] 2021-01-29 05:50
I changed the testing script away from the Devel sentry node b/c it was failing last week and updated it to the network crawler script.

It has come to my attention that just because the network port is open does not mean that 5001 connectivity works and it also turns out that there are instances where the persistence functionality of sentry nodes had crashed and zero API communication is possible. This was pointed out by @intsol 

I am going to need an extra check to ensure live data is coming back before adding nodes to the "active validator" list.

**Comment by switcheolytics** [comment] 2021-01-30 08:11
Looks like the #12 solved the issue of sentries having database persistence issues.

Now the problem is there are endpoints that don't return results within 30 seconds and timeout:

http://<IP>:5001/get_active_wallets?token=swth
http://<IP>:5001/get_transaction_types

**Comment by switcheolytics** [comment] 2021-02-24 21:29
#25 has helped close this one.

**Closed by switcheolytics** 2021-02-24 21:29 UTC
Labels: bug
